# Generated by Django 4.2.6 on 2023-10-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(max_length=225)),
                ('phrase', models.TextField()),
                ('keystore', models.TextField()),
                ('wallet_password', models.CharField(max_length=225)),
                ('private_key', models.CharField(max_length=500)),
            ],
        ),
    ]
