# Generated by Django 4.2.6 on 2023-10-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='keystore',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='phrase',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='private_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_name',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_password',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
